<?php
$produits = array(
	array(
		"id" => 1,
		"rubrique_id" => 22,
		"fournisseur_id" => 3,
		"libelle_court" => "TBPro",
		"libelle_long" => "the box pro",
		"reference_fournisseur" => "Musique Percussion",
		"photo_produit" => "TBPro.jpg",
		"prix_achat" => 36.0000,
		"prix_hors_taxe" => 46.4000,
	),
	array(
		"id" => 2,
		"rubrique_id" => 22,
		"fournisseur_id" => 4,
		"libelle_court" => "HKA",
		"libelle_long" => "HK Audio",
		"reference_fournisseur" => "Vivre Art Loux",
		"photo_produit" => "HKA.jpg",
		"prix_achat" => 400.0000,
		"prix_hors_taxe" => 495.2000,
	),
	array(
		"id" => 3,
		"rubrique_id" => 22,
		"fournisseur_id" => 1,
		"libelle_court" => "FBTHX",
		"libelle_long" => "FBT HIMaxX60",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "FBTHX.jpg",
		"prix_achat" => 575.0000,
		"prix_hors_taxe" => 639.2000,
	),
	array(
		"id" => 4,
		"rubrique_id" => 23,
		"fournisseur_id" => 2,
		"libelle_court" => "SM58",
		"libelle_long" => "Shure",
		"reference_fournisseur" => "Comme aux Musiques",
		"photo_produit" => "SM58.jpg",
		"prix_achat" => 70.0000,
		"prix_hors_taxe" => 78.4000,
	),
	array(
		"id" => 5,
		"rubrique_id" => 23,
		"fournisseur_id" => 5,
		"libelle_court" => "TTBone",
		"libelle_long" => "the t.bone",
		"reference_fournisseur" => "Le Musique en ville",
		"photo_produit" => "TTBone.jpg",
		"prix_achat" => 20.0000,
		"prix_hors_taxe" => 31.2000,
	),
	array(
		"id" => 6,
		"rubrique_id" => 23,
		"fournisseur_id" => 3,
		"libelle_court" => "E835S",
		"libelle_long" => "Senheiser",
		"reference_fournisseur" => "Musique Percussion",
		"photo_produit" => "E835S.jpg",
		"prix_achat" => 60.0000,
		"prix_hors_taxe" => 70.4000,
	),
	array(
		"id" => 7,
		"rubrique_id" => 24,
		"fournisseur_id" => 2,
		"libelle_court" => "X2222USB",
		"libelle_long" => "Behringer Xenyx",
		"reference_fournisseur" => "Comme aux Musiques",
		"photo_produit" => "X2222USB.jpg",
		"prix_achat" => 150.0000,
		"prix_hors_taxe" => 215.2000,
	),
	array(
		"id" => 8,
		"rubrique_id" => 24,
		"fournisseur_id" => 4,
		"libelle_court" => "TTMix",
		"libelle_long" => "the t.mix xmix",
		"reference_fournisseur" => "Vivre Art Loux",
		"photo_produit" => "TTMix.jpg",
		"prix_achat" => 105.0000,
		"prix_hors_taxe" => 94.4000,
	),
	array(
		"id" => 9,
		"rubrique_id" => 24,
		"fournisseur_id" => 1,
		"libelle_court" => "12MTK",
		"libelle_long" => "Soundcraft Signature",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "12MTK.jpg",
		"prix_achat" => 300.0000,
		"prix_hors_taxe" => 355.2000,
	),
	array(
		"id" => 10,
		"rubrique_id" => 18,
		"fournisseur_id" => 4,
		"libelle_court" => "FR4XBK",
		"libelle_long" => "Roland",
		"reference_fournisseur" => "Vivre Art Loux",
		"photo_produit" => "FR4XBK.jpg",
		"prix_achat" => 1900.0000,
		"prix_hors_taxe" => 2767.2000,
	),
	array(
		"id" => 11,
		"rubrique_id" => 18,
		"fournisseur_id" => 1,
		"libelle_court" => "MKII",
		"libelle_long" => "Startone Piano Accordion",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "MKII.jpg",
		"prix_achat" => 300.0000,
		"prix_hors_taxe" => 423.2000,
	),
	array(
		"id" => 12,
		"rubrique_id" => 18,
		"fournisseur_id" => 3,
		"libelle_court" => "SAPHIR",
		"libelle_long" => "Weltmeister",
		"reference_fournisseur" => "Musique Percussion",
		"photo_produit" => "SAPHIR.jpg",
		"prix_achat" => 2800.0000,
		"prix_hors_taxe" => 3119.2000,
	),
	array(
		"id" => 13,
		"rubrique_id" => 19,
		"fournisseur_id" => 2,
		"libelle_court" => "SALDEL",
		"libelle_long" => "Salvi",
		"reference_fournisseur" => "Comme aux Musiques",
		"photo_produit" => "SALDEL.jpg",
		"prix_achat" => 3000.0000,
		"prix_hors_taxe" => 3432.0000,
	),
	array(
		"id" => 14,
		"rubrique_id" => 19,
		"fournisseur_id" => 5,
		"libelle_court" => "SQB",
		"libelle_long" => "Thomann SQB",
		"reference_fournisseur" => "Le Musique en ville",
		"photo_produit" => "SQB.jpg",
		"prix_achat" => 300.0000,
		"prix_hors_taxe" => 398.4000,
	),
	array(
		"id" => 15,
		"rubrique_id" => 19,
		"fournisseur_id" => 1,
		"libelle_court" => "MLL",
		"libelle_long" => "Auris My Little Lyre",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "MLL.jpg",
		"prix_achat" => 80.0000,
		"prix_hors_taxe" => 116.0000,
	),
	array(
		"id" => 16,
		"rubrique_id" => 20,
		"fournisseur_id" => 4,
		"libelle_court" => "111VN",
		"libelle_long" => "Thomann Double Bass",
		"reference_fournisseur" => "Vivre Art Loux",
		"photo_produit" => "111VN.jpg",
		"prix_achat" => 500.0000,
		"prix_hors_taxe" => 599.2000,
	),
	array(
		"id" => 17,
		"rubrique_id" => 20,
		"fournisseur_id" => 3,
		"libelle_court" => "DDB",
		"libelle_long" => "Duke Didi Beck",
		"reference_fournisseur" => "Musique Percussion",
		"photo_produit" => "DDB.jpg",
		"prix_achat" => 2000.0000,
		"prix_hors_taxe" => 2239.2000,
	),
	array(
		"id" => 18,
		"rubrique_id" => 20,
		"fournisseur_id" => 2,
		"libelle_court" => "BKRD",
		"libelle_long" => "Thomann Rockabilly Psycho",
		"reference_fournisseur" => "Comme Aux Musiques",
		"photo_produit" => "BKRD.jpg",
		"prix_achat" => 600.0000,
		"prix_hors_taxe" => 872.0000,
	),
	array(
		"id" => 19,
		"rubrique_id" => 2,
		"fournisseur_id" => 1,
		"libelle_court" => "20HSS",
		"libelle_long" => "Harley Benton",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "20HSS.jpg",
		"prix_achat" => 60.0000,
		"prix_hors_taxe" => 87.2000,
	),
	array(
		"id" => 20,
		"rubrique_id" => 2,
		"fournisseur_id" => 4,
		"libelle_court" => "EBBK",
		"libelle_long" => "Fender Jim Root",
		"reference_fournisseur" => "Vivre Art Loux",
		"photo_produit" => "EBBK.jpg",
		"prix_achat" => 1200.0000,
		"prix_hors_taxe" => 1650.0000,
	),
	array(
		"id" => 21,
		"rubrique_id" => 2,
		"fournisseur_id" => 2,
		"libelle_court" => "MH10",
		"libelle_long" => "ESP LTD",
		"reference_fournisseur" => "Comme aux Musiques",
		"photo_produit" => "MH10.jpg",
		"prix_achat" => 100.0000,
		"prix_hors_taxe" => 191.2000,
	),
	array(
		"id" => 22,
		"rubrique_id" => 3,
		"fournisseur_id" => 5,
		"libelle_court" => "GL2NT",
		"libelle_long" => "Harley Benton Guitarlele",
		"reference_fournisseur" => "Le Musique en ville",
		"photo_produit" => "GL2NT.jpg",
		"prix_achat" => 30.0000,
		"prix_hors_taxe" => 47.2000,
	),
	array(
		"id" => 23,
		"rubrique_id" => 3,
		"fournisseur_id" => 2,
		"libelle_court" => "CG851",
		"libelle_long" => "Startone Pink",
		"reference_fournisseur" => "Comme aux Musiques",
		"photo_produit" => "CG851.jpg",
		"prix_achat" => 22.0000,
		"prix_hors_taxe" => 30.4000,
	),
	array(
		"id" => 24,
		"rubrique_id" => 3,
		"fournisseur_id" => 4,
		"libelle_court" => "GL1",
		"libelle_long" => "Yamaha",
		"reference_fournisseur" => "Vivre Art Loux",
		"photo_produit" => "GL1.jpg",
		"prix_achat" => 48.0000,
		"prix_hors_taxe" => 68.0000,
	),
	array(
		"id" => 25,
		"rubrique_id" => 4,
		"fournisseur_id" => 3,
		"libelle_court" => "BT2E",
		"libelle_long" => "Taylor Baby Mahogany",
		"reference_fournisseur" => "Musique Percussion",
		"photo_produit" => "BT2E.jpg",
		"prix_achat" => 300.0000,
		"prix_hors_taxe" => 399.2000,
	),
	array(
		"id" => 26,
		"rubrique_id" => 4,
		"fournisseur_id" => 1,
		"libelle_court" => "LJ10",
		"libelle_long" => "Furch",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "LJ10.jpg",
		"prix_achat" => 700.0000,
		"prix_hors_taxe" => 990.0000,
	),
	array(
		"id" => 27,
		"rubrique_id" => 4,
		"fournisseur_id" => 2,
		"libelle_court" => "ME2BK",
		"libelle_long" => "Lava Music",
		"reference_fournisseur" => "Comme aux Musiques",
		"photo_produit" => "ME2BK.jpg",
		"prix_achat" => 400.0000,
		"prix_hors_taxe" => 479.2000,
	),
	array(
		"id" => 28,
		"rubrique_id" => 9,
		"fournisseur_id" => 1,
		"libelle_court" => "Yab1",
		"libelle_long" => "Yamaha b1 PE",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Yamaha b1 PE.jpg",
		"prix_achat" => 3075.0000,
		"prix_hors_taxe" => 3690.0000,
	),
	array(
		"id" => 29,
		"rubrique_id" => 9,
		"fournisseur_id" => 1,
		"libelle_court" => "Yab3",
		"libelle_long" => "Yamaha b3 PE",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Yamaha b3 PE.jgp",
		"prix_achat" => 4825.0000,
		"prix_hors_taxe" => 5790.0000,
	),
	array(
		"id" => 30,
		"rubrique_id" => 9,
		"fournisseur_id" => 1,
		"libelle_court" => "Kak15",
		"libelle_long" => "Kawai K15 E EP",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Kawai K15 E EP.jpg",
		"prix_achat" => 3325.0000,
		"prix_hors_taxe" => 3990.0000,
	),
	array(
		"id" => 31,
		"rubrique_id" => 10,
		"fournisseur_id" => 2,
		"libelle_court" => "KaGL10",
		"libelle_long" => "Kawai GL 10 EP",
		"reference_fournisseur" => "Comme aux Musiques",
		"photo_produit" => "Kawai GL 10 EP.jpg",
		"prix_achat" => 9075.0000,
		"prix_hors_taxe" => 10890.0000,
	),
	array(
		"id" => 32,
		"rubrique_id" => 10,
		"fournisseur_id" => 2,
		"libelle_court" => "YaC3",
		"libelle_long" => "Yamaha C3X PE",
		"reference_fournisseur" => "Comme aux Musiques",
		"photo_produit" => "Yamaha C3X PE.jpg",
		"prix_achat" => 24990.0000,
		"prix_hors_taxe" => 29990.0000,
	),
	array(
		"id" => 33,
		"rubrique_id" => 10,
		"fournisseur_id" => 2,
		"libelle_court" => "SeB211",
		"libelle_long" => "Steinway & Sons B221",
		"reference_fournisseur" => "Comme aux Musiques",
		"photo_produit" => "Steinway & Sons B221.jpg",
		"prix_achat" => 44416.0000,
		"prix_hors_taxe" => 53300.0000,
	),
	array(
		"id" => 34,
		"rubrique_id" => 11,
		"fournisseur_id" => 3,
		"libelle_court" => "ThDP95",
		"libelle_long" => "Thomann DP95",
		"reference_fournisseur" => "Musique Percussion",
		"photo_produit" => "Thomann DP95.jpg",
		"prix_achat" => 4825.0000,
		"prix_hors_taxe" => 5790.0000,
	),
	array(
		"id" => 35,
		"rubrique_id" => 11,
		"fournisseur_id" => 3,
		"libelle_court" => "HeDP501",
		"libelle_long" => "Hemingway DP501",
		"reference_fournisseur" => "Musiques Percussion",
		"photo_produit" => "Hemingway DP501.jpg",
		"prix_achat" => 425.0000,
		"prix_hors_taxe" => 511.0000,
	),
	array(
		"id" => 36,
		"rubrique_id" => 11,
		"fournisseur_id" => 3,
		"libelle_court" => "KaCN29",
		"libelle_long" => "Kawai CN29",
		"reference_fournisseur" => "Musiques Percussion",
		"photo_produit" => "Kawai CN29.png",
		"prix_achat" => 1132.0000,
		"prix_hors_taxe" => 1359.0000,
	),
	array(
		"id" => 37,
		"rubrique_id" => 13,
		"fournisseur_id" => 4,
		"libelle_court" => "YaYAS280",
		"libelle_long" => "Yamaha YAS280",
		"reference_fournisseur" => "Vivre Art Loux",
		"photo_produit" => "Yamaha YAS280.jpg",
		"prix_achat" => 825.0000,
		"prix_hors_taxe" => 990.0000,
	),
	array(
		"id" => 38,
		"rubrique_id" => 13,
		"fournisseur_id" => 4,
		"libelle_court" => "ThTAS180",
		"libelle_long" => "Thomann TAS180",
		"reference_fournisseur" => "Vivre Art Loux",
		"photo_produit" => "Thomann TAS180.jpg",
		"prix_achat" => 248.0000,
		"prix_hors_taxe" => 298.0000,
	),
	array(
		"id" => 39,
		"rubrique_id" => 13,
		"fournisseur_id" => 4,
		"libelle_court" => "StSAS75",
		"libelle_long" => "Startone SAS75",
		"reference_fournisseur" => "Vivre Art Loux",
		"photo_produit" => "Startone SAS75.jpg",
		"prix_achat" => 224.0000,
		"prix_hors_taxe" => 269.0000,
	),
	array(
		"id" => 40,
		"rubrique_id" => 14,
		"fournisseur_id" => 5,
		"libelle_court" => "ThTR5BB",
		"libelle_long" => "Thomann TR5BB",
		"reference_fournisseur" => "Le Musique en ville",
		"photo_produit" => "Thomann TR5BB.jpg",
		"prix_achat" => 107.5000,
		"prix_hors_taxe" => 129.0000,
	),
	array(
		"id" => 41,
		"rubrique_id" => 14,
		"fournisseur_id" => 5,
		"libelle_court" => "ThTR200",
		"libelle_long" => "Thomann TR200BB",
		"reference_fournisseur" => "Le Musique en ville",
		"photo_produit" => "Thomman TR200BB.jpg",
		"prix_achat" => 132.5000,
		"prix_hors_taxe" => 159.0000,
	),
	array(
		"id" => 42,
		"rubrique_id" => 14,
		"fournisseur_id" => 5,
		"libelle_court" => "BaTR450",
		"libelle_long" => "Bach TR450S",
		"reference_fournisseur" => "Le Musique en ville",
		"photo_produit" => "Bach TR450S.jpg",
		"prix_achat" => 640.0000,
		"prix_hors_taxe" => 769.0000,
	),
	array(
		"id" => 43,
		"rubrique_id" => 15,
		"fournisseur_id" => 1,
		"libelle_court" => "Th12H",
		"libelle_long" => "Thomann 12H",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Thomman 12H.jpg",
		"prix_achat" => 16.5000,
		"prix_hors_taxe" => 19.9000,
	),
	array(
		"id" => 44,
		"rubrique_id" => 15,
		"fournisseur_id" => 1,
		"libelle_court" => "ThAC",
		"libelle_long" => "Thomann ACStein",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Thomann ACStein.jpg",
		"prix_achat" => 82.5000,
		"prix_hors_taxe" => 99.0000,
	),
	array(
		"id" => 45,
		"rubrique_id" => 15,
		"fournisseur_id" => 1,
		"libelle_court" => "ThZFAN",
		"libelle_long" => "Thomann Zfan",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Thomann Zfan.jpg",
		"prix_achat" => 45.8000,
		"prix_hors_taxe" => 55.0000,
	),
	array(
		"id" => 46,
		"rubrique_id" => 16,
		"fournisseur_id" => 1,
		"libelle_court" => "ThFL200",
		"libelle_long" => "Thomann FL200",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Thomann FL200.jpg",
		"prix_achat" => 132.5000,
		"prix_hors_taxe" => 159.0000,
	),
	array(
		"id" => 47,
		"rubrique_id" => 16,
		"fournisseur_id" => 1,
		"libelle_court" => "MuEX",
		"libelle_long" => "Muramatsu EX",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Muramatsu EX.jpg",
		"prix_achat" => 3333.0000,
		"prix_hors_taxe" => 3999.0000,
	),
	array(
		"id" => 48,
		"rubrique_id" => 16,
		"fournisseur_id" => 1,
		"libelle_court" => "PePF505",
		"libelle_long" => "Pearl PF505",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Pearl PF505.jpg",
		"prix_achat" => 462.0000,
		"prix_hors_taxe" => 555.0000,
	),
	array(
		"id" => 49,
		"rubrique_id" => 26,
		"fournisseur_id" => 1,
		"libelle_court" => "ETC S4 PAR EA",
		"libelle_long" => "ETC S4 PAR EA",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "ETC.jpg",
		"prix_achat" => 150.0000,
		"prix_hors_taxe" => 256.8000,
	),
	array(
		"id" => 50,
		"rubrique_id" => 26,
		"fournisseur_id" => 1,
		"libelle_court" => "Eurolite LED SL-400",
		"libelle_long" => "Eurolite LED SL-400 DMX Search Light",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Eurolite.jpg",
		"prix_achat" => 1200.0000,
		"prix_hors_taxe" => 1500.0000,
	),
	array(
		"id" => 51,
		"rubrique_id" => 26,
		"fournisseur_id" => 1,
		"libelle_court" => "Cameo Matrix 10W",
		"libelle_long" => "Cameo Matrix Panel 10 W RGB",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Cameo.jpg",
		"prix_achat" => 400.0000,
		"prix_hors_taxe" => 431.2000,
	),
	array(
		"id" => 52,
		"rubrique_id" => 27,
		"fournisseur_id" => 1,
		"libelle_court" => "Stairville 132 LED RGB",
		"libelle_long" => "Stairville Wild Wash 132 LED RGB",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Stairville.jpg",
		"prix_achat" => 50.0000,
		"prix_hors_taxe" => 63.2000,
	),
	array(
		"id" => 53,
		"rubrique_id" => 27,
		"fournisseur_id" => 1,
		"libelle_court" => "Martin Atomic",
		"libelle_long" => "Martin Atomic 3000 LED",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Martin.jpg",
		"prix_achat" => 1900.0000,
		"prix_hors_taxe" => 2318.4000,
	),
	array(
		"id" => 54,
		"rubrique_id" => 27,
		"fournisseur_id" => 1,
		"libelle_court" => "Varytec Colors",
		"libelle_long" => "Varytec Colors SonicStrobe",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Varytec.jpg",
		"prix_achat" => 100.0000,
		"prix_hors_taxe" => 141.6000,
	),
	array(
		"id" => 55,
		"rubrique_id" => 28,
		"fournisseur_id" => 1,
		"libelle_court" => "Laserworld DS-1000RGB",
		"libelle_long" => "Laserworld DS-1000RGB MK3",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Laserworld.jpg",
		"prix_achat" => 500.0000,
		"prix_hors_taxe" => 596.0000,
	),
	array(
		"id" => 56,
		"rubrique_id" => 28,
		"fournisseur_id" => 1,
		"libelle_court" => "ADj Stinger",
		"libelle_long" => "ADJ Stinger II",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "ADj.jpg",
		"prix_achat" => 150.0000,
		"prix_hors_taxe" => 172.0000,
	),
	array(
		"id" => 57,
		"rubrique_id" => 28,
		"fournisseur_id" => 4,
		"libelle_court" => "Laserworld PL",
		"libelle_long" => "Laserworld PL-5000RGB MK2",
		"reference_fournisseur" => "Vivre Art Loux",
		"photo_produit" => "Laserworld1.jpg",
		"prix_achat" => 1900.0000,
		"prix_hors_taxe" => 2199.2000,
	),
	array(
		"id" => 58,
		"rubrique_id" => 30,
		"fournisseur_id" => 4,
		"libelle_court" => "Gravity LTS",
		"libelle_long" => "Gravity LTS 01 B Set",
		"reference_fournisseur" => "Vivre Art Loux",
		"photo_produit" => "Gravity.jpg",
		"prix_achat" => 40.0000,
		"prix_hors_taxe" => 61.6000,
	),
	array(
		"id" => 59,
		"rubrique_id" => 30,
		"fournisseur_id" => 4,
		"libelle_court" => "Roadworx Electric",
		"libelle_long" => "Roadworx Multi Electric Stand",
		"reference_fournisseur" => "Vivre Art Loux",
		"photo_produit" => "Roadworx.jpg",
		"prix_achat" => 200.0000,
		"prix_hors_taxe" => 231.2000,
	),
	array(
		"id" => 60,
		"rubrique_id" => 30,
		"fournisseur_id" => 1,
		"libelle_court" => "Standback",
		"libelle_long" => "Standback Ampstand",
		"reference_fournisseur" => "Musique",
		"photo_produit" => "Standback.jpg",
		"prix_achat" => 15.0000,
		"prix_hors_taxe" => 23.2000,
	),
	array(
		"id" => 61,
		"rubrique_id" => 31,
		"fournisseur_id" => 3,
		"libelle_court" => "Millenium MDT5S-Pro",
		"libelle_long" => "Millenium MDT5S-Pro Drum Throne Saddle",
		"reference_fournisseur" => "Musique Percussion",
		"photo_produit" => "Millenium.jpg",
		"prix_achat" => 50.0000,
		"prix_hors_taxe" => 55.2000,
	),
	array(
		"id" => 62,
		"rubrique_id" => 31,
		"fournisseur_id" => 3,
		"libelle_court" => "Mapex MXT765ASER ",
		"libelle_long" => "Mapex MXT765ASER Drum Stool",
		"reference_fournisseur" => "Musique Percussion",
		"photo_produit" => "Mapex.jpg",
		"prix_achat" => 100.0000,
		"prix_hors_taxe" => 127.2000,
	),
	array(
		"id" => 63,
		"rubrique_id" => 31,
		"fournisseur_id" => 3,
		"libelle_court" => "DW 9120AL",
		"libelle_long" => "DW 9120AL Drum Stool",
		"reference_fournisseur" => "Musique Percussion",
		"photo_produit" => "DW.jpg",
		"prix_achat" => 200.0000,
		"prix_hors_taxe" => 255.2000,
	),
	array(
		"id" => 64,
		"rubrique_id" => 32,
		"fournisseur_id" => 3,
		"libelle_court" => "Boss Guitar Headphones",
		"libelle_long" => "Boss Waza Air Guitar Headphones",
		"reference_fournisseur" => "Vivre Art Loux",
		"photo_produit" => "Boss.jpg",
		"prix_achat" => 250.0000,
		"prix_hors_taxe" => 303.2000,
	),
	array(
		"id" => 65,
		"rubrique_id" => 32,
		"fournisseur_id" => 3,
		"libelle_court" => "Metrophones MPD-G",
		"libelle_long" => "Metrophones MPD-G Headphones LCD Metronom",
		"reference_fournisseur" => "Musique Percussion",
		"photo_produit" => "Metrophones.jpg",
		"prix_achat" => 120.0000,
		"prix_hors_taxe" => 168.8000,
	),
	array(
		"id" => 66,
		"rubrique_id" => 32,
		"fournisseur_id" => 5,
		"libelle_court" => "Superlux HD-681",
		"libelle_long" => "Superlux HD-681",
		"reference_fournisseur" => "Le musique en ville",
		"photo_produit" => "Superlux.jpg",
		"prix_achat" => 10.0000,
		"prix_hors_taxe" => 18.0800,
	),
	array(
		"id" => 67,
		"rubrique_id" => 6,
		"fournisseur_id" => 3,
		"libelle_court" => "Pearl EXX725SBR/C",
		"libelle_long" => "Pearl EXX725SBR/C Export Aztec Gold",
		"reference_fournisseur" => "Musique Percussion",
		"photo_produit" => "Pearl.jpg",
		"prix_achat" => 450.0000,
		"prix_hors_taxe" => 599.2000,
	),
	array(
		"id" => 68,
		"rubrique_id" => 6,
		"fournisseur_id" => 3,
		"libelle_court" => "Tama Star Bubinga",
		"libelle_long" => "Tama STAR Drum Bubinga White Ebony",
		"reference_fournisseur" => "Musique Percussion",
		"photo_produit" => "Tama.jpg",
		"prix_achat" => 6000.0000,
		"prix_hors_taxe" => 7199.2000,
	),
	array(
		"id" => 69,
		"rubrique_id" => 6,
		"fournisseur_id" => 5,
		"libelle_court" => "Sonor AQX Jungle",
		"libelle_long" => "Sonor AQX Jungle Set BOS",
		"reference_fournisseur" => "La musique en ville",
		"photo_produit" => "Sonor.jpg",
		"prix_achat" => 350.0000,
		"prix_hors_taxe" => 399.2000,
	),
	array(
		"id" => 70,
		"rubrique_id" => 7,
		"fournisseur_id" => 2,
		"libelle_court" => "Roland VAD706-GC Bundle",
		"libelle_long" => "Roland VAD706-GC E-Drum Set Bundle",
		"reference_fournisseur" => "Comme aux Musiques",
		"photo_produit" => "Roland.jpg",
		"prix_achat" => 6000.0000,
		"prix_hors_taxe" => 6872.0000,
	),
	array(
		"id" => 71,
		"rubrique_id" => 7,
		"fournisseur_id" => 3,
		"libelle_court" => "Alesis Strike Pro",
		"libelle_long" => "Alesis Strike Pro Special Edition",
		"reference_fournisseur" => "Musique Percussion",
		"photo_produit" => "Alesis.jpg",
		"prix_achat" => 1500.0000,
		"prix_hors_taxe" => 1887.2000,
	),
	array(
		"id" => 72,
		"rubrique_id" => 7,
		"fournisseur_id" => 3,
		"libelle_court" => "Millenium E-Drum Set",
		"libelle_long" => "Millenium HD-120 E-Drum Set",
		"reference_fournisseur" => "Musique Percussion",
		"photo_produit" => "Millenium1.jpg",
		"prix_achat" => 100.0000,
		"prix_hors_taxe" => 158.4000,
	),
);
?>